version: 1.0.0.{build}

branches:
  except:
    - project/travis
    - project/docs
    - feature/experiments

environment:
  vlcqt_version: 1.0.0
  vlc_version: 2.2.1

  matrix:
  # MSVC x86
  - name: win32
    platform: amd64_x86
    qt: 5.5\msvc2013
    suffix: msvc2013

  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.5\msvc2013_64
    suffix: msvc2013

  # MSVC x64 (Qt 5.4)
  - name: win64
    platform: amd64
    qt: 5.4\msvc2013_64_opengl
    suffix: msvc2013_5.4

  # MinGW
  - name: win32
    platform: mingw
    qt: 5.5\mingw492_32
    suffix: mingw

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - set ORIGPATH=%PATH%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")
  - if %APPVEYOR_REPO_TAG%==true (set nogitinfo=ON) else (set nogitinfo=OFF)

clone_folder: c:\dev\vlc-qt

install:
  - cd c:\dev
  - md install
  - md dependencies
  - cd dependencies
  - ps: $vlcdl = 'http://download.videolan.org/vlc/' + $env:vlc_version + '/' + $env:name + '/vlc-' + $env:vlc_version + '-' + $env:name + '.7z'
  - ps: Start-FileDownload $vlcdl -FileName vlc.7z
  - 7z x vlc.7z > NUL
  - move vlc-* vlc-%name%
  - cd vlc-%name%
  - if not %platform%==mingw call ..\..\vlc-qt\tools\win_vlc_symbols_%name%.bat

before_build:
  - cd c:\dev\vlc-qt
  - md build-release
  - md build-debug

build_script:
  - if %platform%==mingw set PATH=C:\Qt\%qt%\bin;C:\Qt\Tools\mingw492_32\bin;C:\Program Files (x86)\CMake\bin
  - cd build-release
  - cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="c:/dev/install" -DCI=ON -DNO_GIT=%nogitinfo% -DBUILD_TESTS=ON -DLIBVLC_LIBRARY="c:/dev/dependencies/vlc-%name%/sdk/lib/libvlc.lib" -DLIBVLCCORE_LIBRARY="c:/dev/dependencies/vlc-%name%/sdk/lib/libvlccore.lib" -DLIBVLC_INCLUDE_DIR="c:/dev/dependencies/vlc-%name%/sdk/include"
  - if not %platform%==mingw (nmake) else (mingw32-make)
  - if not %platform%==mingw (nmake install) else (mingw32-make install)
  - cd ..
  - cd build-debug
  - cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="c:/dev/install" -DCI=ON -DNO_GIT=%nogitinfo% -DLIBVLC_LIBRARY="c:/dev/dependencies/vlc-%name%/sdk/lib/libvlc.lib" -DLIBVLCCORE_LIBRARY="c:/dev/dependencies/vlc-%name%/sdk/lib/libvlccore.lib" -DLIBVLC_INCLUDE_DIR="c:/dev/dependencies/vlc-%name%/sdk/include"
  - if not %platform%==mingw (nmake) else (mingw32-make)
  - if not %platform%==mingw (nmake install) else (mingw32-make install)
  - if %platform%==mingw set PATH=%ORIGPATH%

after_build:
  - cd c:\dev\install
  - if %APPVEYOR_REPO_TAG%==true (set buildname=%vlcqt_version%) else (set buildname=%vlcqt_version%_build%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_REPO_COMMIT:~0,7%)
  - 7z a ..\vlc-qt\VLC-Qt_%buildname%_%name%_%suffix%.7z bin lib include
  - 7z a ..\vlc-qt\VLC-Qt_Test_%buildname%_%name%_%suffix%.7z test > NUL
  - cd c:\dev\vlc-qt

test_script:
  - cd c:\dev\install\test
  - start /wait VLC-Qt.exe test
  - cd c:\dev\vlc-qt

artifacts:
  - path: '*.7z'
