os:
  - linux
  - osx

branches:
  except:
    - project/appveyor
    - feature/experiments

language: cpp

before_install: . tools/ci/$TRAVIS_OS_NAME/before_install.sh
install: . tools/ci/$TRAVIS_OS_NAME/install.sh
script: . tools/ci/$TRAVIS_OS_NAME/script.sh
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && . tools/ci/$TRAVIS_OS_NAME/after_success.sh || true'

addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
   packages:
    - gcc-4.8
    - g++-4.8
    - libqt4-dev
    - libvlc-dev
    - libvlccore-dev
    - vlc
    - p7zip-full
